### ISSUE TITLE
configure ssh options

### ISSUE THREAD

**Issue by JoseMontesRicardo** [flipxfx/download-git-repo#11]
how to configure ssh option {clone:true} for bitbucket?.
pdt : i generated ssh key

**Comment by flipxfx** [comment]
This is part of BitBucket itself. If you have it setup correctly on your machine it will work.

https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html
https://www.atlassian.com/git/tutorials/install-git
