### ISSUE TITLE
the repo download is not the latest

### ISSUE THREAD

**Issue by shangxinbo** [flipxfx/download-git-repo#15]
when I use vue-cli to download my template,it use 'download-git-repo'，I find that my template(shangxinbo/vue-init) is not the latest.when I change it to 'shangxinbo/vue-init#master',it's the latest.Why？ dose download-git-repo download repo on master branch default? or Cache ?  please help me

**Comment by flipxfx** [comment]
It defaults to master https://github.com/flipxfx/download-git-repo/blob/master/index.js#L62. Not sure what could be causing that. Can you double check by writing it to 2 different folders?

**Comment by nerdenough** [comment]
@shangxinbo The issue is vuejs/vue-cli#409 - also having this issue in [phaser-cli](npmjs.com/package/phaser-cli) (based on vue-cli) and is not a `download-git-repo` issue.

**Comment by flipxfx** [comment]
Ah ok thanks for figuring that out.

**Comment by shangxinbo** [comment]
thanks
