### ISSUE TITLE
git-clone shallow option

### ISSUE THREAD

**Issue by steven-klein** [flipxfx/download-git-repo#16]
Since the .git directory is nuked when using the clone option, does it make sense to bake in git-clone's shallow option to speed up the cloning?

**Comment by flipxfx** [comment]
Nice I didn't notice that. I'll add it in!

**Comment by flipxfx** [comment]
This will not work for anything other than the master branch but I can add that in.

**Comment by flipxfx** [comment]
Fixed with 8688d619eea24aedcf1d08de50f468fc1bfeeb5f
