### ISSUE TITLE
No authentication

### ISSUE THREAD

**Issue by nianhua110** [flipxfx/download-git-repo#26]
> ⠋ downloading template
> /usr/lib/node_modules/vue-cli/node_modules/.5.7.1@got/index.js:221
> 			throw new Error('Basic authentication must be done with auth option');
> 			^
> 
> Error: Basic authentication must be done with auth option
>     at normalizeArguments (/usr/lib/node_modules/vue-cli/node_modules/.5.7.1@got/index.js:221:10)
>     at Function.got.stream (/usr/lib/node_modules/vue-cli/node_modules/.5.7.1@got/index.js:350:18)
>     at Download.<anonymous> (/usr/lib/node_modules/vue-cli/node_modules/.4.4.3@download/index.js:126:20)
>     at runCallback (timers.js:657:20)
>     at tryOnImmediate (timers.js:624:5)
>     at processImmediate [as _immediateCallback] (timers.js:596:5)
> 

how can I resolve it ?

**Comment by flipxfx** [comment]
what's your input?

**Comment by flipxfx** [comment]
Closing due to no response
