### ISSUE TITLE
 download “image 、fonts woff svg” type file is wrong，not origin file。

### ISSUE THREAD

**Issue by lyboy2012** [flipxfx/download-git-repo#27]
download “image 、fonts woff svg” type file is wrong，not origin file。

**Comment by flipxfx** [comment]
What? Open an issue with some more information if you need help....

**Comment by lyboy2012** [comment]
sorry,it's my fault。
\`fs.createReadStream(uri).pipe(replaceStream('{name}', replace)).pipe(fs.createWriteStream(target))` 
when replacestream image svg will create wrong file. sorry!

**Comment by flipxfx** [comment]
Still not following. If it’s an issue with the download or git-clone package please open an issue there.
