### ISSUE TITLE
gitlab does not work

### ISSUE THREAD

**Issue by zhouytforever** [flipxfx/download-git-repo#28]
When I run 
`download('gitlab:my-gitlab-ip:my-name/my-project#my-branch', 'test/tmp', function (err) {
  console.log(err ? 'Error' : 'Success')
})`

I got the error 
`/Users/myHome/.config/yarn/global/node_modules/got/index.js:205
			throw new Error('Basic authentication must be done with auth option');`

**Comment by flipxfx** [comment]
Is the project public? If not, you'll need to use the clone option and make sure you have your SSH keys setup.

**Comment by flipxfx** [comment]
Closing after no response.
