### ISSUE TITLE
Downloading private repo without 'clone' option

### ISSUE THREAD

**Issue by andrey-hohlov** [flipxfx/download-git-repo#3]
If download private repo without `clone` options it's make zip arhive (master.zip) in dest folder. And no errors.

When I open the archive there is of cource an error (wrong format).

I thins there is need an error message if we tru download private repositiory without clone.

Using Download [.use](https://github.com/kevva/download#useplugin) I loged response headers and status.

Test with bitbucket. Private and public repo show 200 status. But there is different in headers.

Private

```
{ 
  server: 'nginx/1.6.2',
  vary: 'Cookie, Accept-Language',
  'cache-control': 'max-age=0',
  'content-type': 'text/html; charset=utf-8',
  'content-encoding': 'gzip',
  'strict-transport-security': 'max-age=31536000',
  date: 'Sat, 16 Jan 2016 05:32:01 GMT',
  'x-served-by': 'app-104',
  expires: 'Sat, 16 Jan 2016 05:32:01 GMT',
  'transfer-encoding': 'chunked',
  'content-language': 'en',
  'x-static-version': 'cb7c09ad73aa',
  'x-content-type-options': 'nosniff',
  'x-render-time': '0.0132629871368',
  connection: 'close',
  'set-cookie': [ 'csrftoken=pN067htBnfhicx86v4rkZfOwFbw0u3RD; expires=Sat, 14-Jan-2017 05:32:01 GMT; Max-Age=31449600; Path=/; secure' ],
  'last-modified': 'Sat, 16 Jan 2016 05:32:01 GMT',
  'x-version': 'cb7c09ad73aa',
  'x-request-count': '236',
  'x-frame-options': 'SAMEORIGIN'
}
```

Public

```
{ 
  server: 'nginx/1.6.2',
  'cache-control': 'max-age=900',
  'content-type': 'application/zip; charset=utf-8',
  'strict-transport-security': 'max-age=31536000',
  date: 'Sat, 16 Jan 2016 05:33:36 GMT',
  expires: 'Sat, 16 Jan 2016 05:33:36 GMT',
  'accept-ranges': 'bytes',
  etag: '"5699bc21-5bb"',
  'content-disposition': 'attachment; filename=flipxfx-download-bitbucket-repo-fixture-ff95faeda055.zip',
  connection: 'close',
  'last-modified': 'Sat, 16 Jan 2016 03:42:25 GMT',
  'x-cache-info': 'caching',
  'content-length': '1467' 
}
```

```
'content-type': 'text/html; charset=utf-8',
```

```
 'content-type': 'application/zip; charset=utf-8',
```

I haven't github private repo, but it public also return

```
 'content-type': 'application/zip',
```

Maybe we can test response, and if content-type don't contains application/zip - throw error?

**Comment by flipxfx** [comment]
Yeah it should probably throw an error. I have a friend who has some private repos. I can test it tomorrow and see if it gives the same as Bitbucket.

**Comment by flipxfx** [comment]
I testest a private GitHub repo and it returns a 404 so those aren't an issue. I was able to throw an error with downloads `.use` but it doesn't error cleanly due to this [issue](https://github.com/kevva/download/issues/84). I'd rather wait to fix this issue after download's use is fixed. Even if I throw an error, the master.zip file is still downloaded :(
