### ISSUE TITLE
windows download mygitlab RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by skyweaver213** [flipxfx/download-git-repo#32]
Hello ， my windows os download mygitlab.com  faild  but mac os success even if I delete ssh key. mac os would ask me username and password then I input download success.  windows os won't ask me anything immediate reminder: RequestError: unable to verify the first certificate. 
      if I change https://mygitlab.com/xxx  ,windows os would reminder: Error: 'git clone' failed with status 128. But I download github address would be success. so i  seek help.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/5363176/36955052-0091f04e-2061-11e8-8012-b076f830ea7c.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/5363176/36955115-68a32202-2061-11e8-8318-215a307d48e2.png">

**Comment by flipxfx** [comment]
I'm on a Mac so it's not easy to help you here, but it sounds like this would be more of an issue with https://github.com/jaz303/git-clone

**Comment by skyweaver213** [comment]
I create a New issue ask for git-clone owner, Thanks!

**Comment by caistrong** [comment]
if you use Direct mode like this:

```js
download('direct:https://gitlab.com/flipxfx/download-git-repo-fixture.git', 'test/tmp', { clone: true }, function (err) {
  console.log(err ? 'Error' : 'Success')
})
```
check if you add `{ clone: true}` options
