### ISSUE TITLE
Add some way to mock the download

### ISSUE THREAD

**Issue by kristianmandrup** [flipxfx/download-git-repo#33]
How about using mock-fs or similar/ Would be nice if we could avoid having to do a real download and clean up the FS when testing... Perhaps use [mock-git](https://github.com/stevemao/mock-git)

**Comment by kristianmandrup** [comment]
Also look at: https://github.com/kevva/download/blob/master/test.js#L15

**Comment by flipxfx** [comment]
If you'd like to make a go at this I'll look at the pull request.

**Comment by kristianmandrup** [comment]
Yeah, but not quite sure how tbh.

```js
function configureMocks(options = {}) {
  const { mock } = options
  mock.gitRepoResponse && mock.gitRepoResponse(options)
  mock.fileSystem && mock.fileSystem(options.fs, options)
}

function gitRepoResponse(options = {}) {
   const { route, fixtures, gitBaseUrl } = options
    nock(gitBaseUrl)
      .persist()
      .get(route.userRepoName.invalid)
      .reply(404)
      .get(route.userRepoName.valid)
      .replyWithFile(200, fixtures.zipPath))
}
```

Then I assume that this lib will normally extract the zip received from fx. github into files on local disk. Instead we could just mock the result via something like `mock-fs` so we don'r rely on either a connection or touch any files to keep the test run totally clean.

```js
  import * as mockFs from 'mock-fs'

  const fs = {
    // files.zip
    'files': {
      'foo.txt': 'foo',
      'bar.txt': 'bar',
    }
  }

  const fileSystem = mockFs

  beforeAll(() => {
    const mock = {
      gitRepoResponse,
      fileSystem
    }

    configureMocks({
      mock,
      fs,
      route, 
      fixtures, 
      gitBaseUrl
    })
   })
``` 

What do you think?

**Comment by kristianmandrup** [comment]
I'll try to write a lib shortly to facilitate mocking using this approach.

**Comment by kristianmandrup** [comment]
I started it here as [mock-git-repo-download](https://github.com/kristianmandrup/mock-git-repo-download)

**Comment by Webjiacheng** [comment]
'git clone' failed with status 128，how to resolve？

**Comment by Selinalemon** [comment]
Error: 'git clone' failed with status 128
how to solve this problem? thanks for answering.
