### ISSUE TITLE
Error: 'git clone' failed with status 128

### ISSUE THREAD

**Issue by zhangzs000** [flipxfx/download-git-repo#41]
env: mac
detail:
 i can execute command :
git clone https://github.com/zhangzs000/zs.git locally.
but when i execute in a project, it has a error:

download err:  Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (/Users/bosszhang/Documents/workspace_temp/test-cli/node_modules/_git-clone@0.1.0@git-clone/index.js:33:22)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)

my project code:
// download.js
const path = require('path')
module.exports = function (target) {
  target = path.join(target || '.', '.download-temp')
  return new Promise(function(resolve, reject) {
      download('https://github.com:zhangzs000/zs.git#master',
          target, { clone: true }, (err) => {
        if (err) {
          reject(err)
        } else {
          resolve(target)
        }
      })
    })
}
const download = require('./download')
program.usage('<project-name>').parse(process.argv)
let projectName = program.args[0]
download(rootName)
    .then(target =>console.log('download target: ',target))
    .catch(err =>console.log('download err: ',err))

**Comment by flipxfx** [comment]
This looks like an error directly from git itself. This repo will never handle cleanup if the error is from trying to clone to an existing directory, it's up to the parent code to make sure of this.

**Comment by YanYuanFE** [comment]
not use { clone: true }，this is because you use Https clone。

**Comment by zhangzs000** [comment]
now 404. Resources should exist, but 404.

**Comment by jpinkster** [comment]
@zhangzs000 as noted in this issue, try adding "direct:" before your URL 
https://github.com/flipxfx/download-git-repo/issues/43
