### ISSUE TITLE
Cannot download from Gitlab using vue-cli

### ISSUE THREAD

**Issue by lanshark** [flipxfx/download-git-repo#42]
Vue-cli uses this library to download it's templates, but it fails when using a gitlab template like so:

vue-cli gitlab:lansharkconsulting/my-template

giving a 404 error even if the correct path is given.  Not sure what happens if the path looks like:

lansharkconsulting/wagpress/wagpress-base for example

**Comment by flipxfx** [comment]
This works for me. If the groups or repo are set to private you will need to pass `{ clone: true }`.

**Comment by flipxfx** [comment]
Or you can now send `{ headers: { 'PRIVATE-TOKEN': '1234' } }`

**Comment by LeeRayno** [comment]
@lanshark see https://github.com/vuejs/vue-cli/issues/525#issuecomment-344504097 this maybe helpful

**Comment by flipxfx** [comment]
@lanshark So is this still an issue or just issue with how t get it working?

**Comment by lanshark** [comment]
No idea - I gave up

**Comment by flipxfx** [comment]
Welp
