### ISSUE TITLE
cant download code from gitlab   'Error: 'git clone' failed with status 128'

### ISSUE THREAD

**Issue by ahz549467483** [flipxfx/download-git-repo#44]
Yesterday was good, but today is not. I can't find the reason 
'Error: 'git clone' failed with status 128'

`
#! /usr/bin/env node
const program = require('commander');
const download = require('download-git-repo');
const chalk = require('chalk');
const ora = require('ora');
program
  .version('0.1.0')
  .option('-i, init [name]', '初始化x-build项目')
  .parse(process.argv);

if (program.init) {
  const spinner = ora('正在从gitlab下载x-build').start();
  download('direct:xxx#xxxx', process.cwd(), { clone: true }, function (err) {
    if(!err){
      // 可以输出一些项目成功的信息
      spinner.clear();
      console.info(chalk.blueBright('下载成功'));
      process.exit();
    }else{
      spinner.warn(err);
      process.exit();
    }
  })
}
`

**Comment by xxxxxMiss** [comment]
You may not have writable permission and you can try it as a root permission

**Comment by flipxfx** [comment]
this would be an issue with `git-clone` or git on the machine
