### ISSUE TITLE
Add local gitlab support.

### ISSUE THREAD

**Issue by ajanes93** [flipxfx/download-git-repo#5]
The ability to link to a private local gitlab repo would be great.  I think just allowing a full url to clone would solve this;

```
download('https://git.customdomain.co.uk/user/repo', 'test/tmp', { clone: true }, function(err) {
  if (err) return done(err);
  done();
});
```

**Comment by flipxfx** [comment]
The problem with using the whole URL is that it takes away from what this repo actually does. This repo abstracts the urls needed for git repos on top the [download](https://github.com/kevva/download) module.

Maybe something like `gitlab:host:owner/name` where host is optional?

**Comment by ajanes93** [comment]
You're right.  I think that would do it, this repo is great, I just need to be able to use it with our local gitlab implementation.  Being able to specify the host would solve this.

**Comment by flipxfx** [comment]
Please make sure this update works for you and let me know! I don't have a local GitLab to test with.

**Comment by ajanes93** [comment]
Thanks for this.  I have tested with our local GitLab and it's working as intended! Thanks again.
