### ISSUE TITLE
关于码云

### ISSUE THREAD

**Issue by IHongTaoI** [flipxfx/download-git-repo#52]
请问下怎么下载码云上面的仓库

**Comment by flipxfx** [comment]
Please check the readme or submit another issue with more information on what you are trying to do 😄

**Comment by IHongTaoI** [comment]
how to download the https://gitee.com/ the repositories

**Comment by flipxfx** [comment]
I'm not sure I'll be able to help you here. If it's an issue with authorization, make sure you have your SSH keys setup correctly.

**Comment by Jesonhu** [comment]
@IHongTaoI #43 
地址前面加上 'direct:'
