### ISSUE TITLE
Add Progress support 

### ISSUE THREAD

**Issue by zjzhome** [flipxfx/download-git-repo#6]

**Comment by flipxfx** [comment]
For downloads I'd have to add optional function parameter `data` using `.on('data', data => console.log(data))`. For clones I'm not sure how that would be done. Git clone does spit out progress but I wouldn't really be able to relay that back.

**Comment by flipxfx** [comment]
I'm going to go ahead and close this as I don't think it's necessary. If you'd like to add the ability with a pull request I'll check it out or if more people want it I'll look into it.

**Comment by zjzhome** [comment]
OK, Thank you for your reply
