### ISSUE TITLE
gitlab with custom domain on a dedicated server

### ISSUE THREAD

**Issue by Lacroute** [flipxfx/download-git-repo#9]
Hi,

I'm using [vue-cli](https://github.com/vuejs/vue-cli) to generate a clean template of my project. I wanted to use a custom template so I had to push it online.

I got troubles with gitlab and the custom url of the repo, so I wanted to test it with a github account. Everything work with github, but not with gitlab..

I searched and maybe I found something. I'm working with a gitlab server hosted on an url similar to http://custom.company.com. When I debug your code I got this :

- without `--clone`, `getUrl()` returns :
`https://gitlab.com/custom.company.com/theteam/therepo/repository/archive.zip?ref=master` instead of 
`http://custom.company.com/theteam/therepo/repository/archive.zip?ref=master` (which is working in the browser)

- with `--clone`, `getUrl()` returns :
I got `git@gitlab.com:custom.company.com/theteam/therepo.git` instead of `git@custom.company.com:theteam/therepo.git` and then I got an error `'git clone' failed with status 128`

**Comment by flipxfx** [comment]
Does this not work for you? "In addition to specifying the type of where to download, you can also specify a custom host like gitlab:custom.com:owner/name."

**Comment by flipxfx** [comment]
@Lacroute Any update on this? Did you try my suggestion?

**Comment by flipxfx** [comment]
You can also now do gitlab:http://custom.com:owner/name for a custom protocol.

**Comment by flipxfx** [comment]
Closing no response. Assuming it's fixed.
